version: '1'
name: ter3_1-calculadora
services:
    web:
        image: nginx:1.25
        container_name: web
        ports:
        - 8001:80
        volumes:
        - ./app:/usr/share/nginx/html
        - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        build: ./docker/php/
        volumes:
        - ./app:/usr/share/nginx/html
        - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        - ./docker/php/config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini